include ../../ucfg.mk

obj = src/aabox.o src/chunk.o src/dynarr.o src/extmesh.o src/g3danm.o \
	  src/g3dscn.o src/goat3d.o src/json.o src/log.o src/read.o src/readgltf.o \
	  src/track.o src/util.o src/write.o

alib = libgoat3d.a

CFLAGS = $(CFLAGS_sys) $(CFLAGS_extra) $(OPT_sys) -Iinclude -I.. -I../../src

$(alib): $(obj)
	$(AR) rcs $@ $(obj)

.c.o:
	$(CC) -o $@ $(CFLAGS) -c $<

.PHONY: clean
clean:
	rm -f $(obj) $(alib)

# vi:ft=make:
