include ../../ucfg.mk

obj = src/anim.o src/track.o
alib = libanim.a

CFLAGS = $(CFLAGS_sys) $(CFLAGS_extra) $(OPT_sys) -I.. -I../../src

$(alib): $(obj)
	$(AR) rcs $@ $(obj)

.c.o:
	$(CC) -o $@ $(CFLAGS) -c $<

.PHONY: clean
clean:
	rm -f $(obj) $(alib)

# vi:ft=make:
