name: DOS build (DJGPP)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: cache toolchain
      id: cache-tc
      uses: actions/cache@v4
      with:
        path: djgpp
        key: djgpp-cache1

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpng-dev libjpeg-dev nasm subversion

    - name: install toolchain
      if: steps.cache-tc.outputs.cache-hit != 'true'
      run: |
        wget http://mutantstargoat.com/~nuclear/djgpp_bundle.tar.gz
        tar xzvf djgpp_bundle.tar.gz
        sed -i 's/HOME/GITHUB_WORKSPACE/g' djgpp/setenv

    - name: prepare datafiles
      run: |
        svn export svn://mutantstargoat.com/datadirs/dosdemo data
        tools/procdata
        ln data/bin/libmidas.a libs/midas/libmidas.a

    - name: build demo
      run: |
        source djgpp/setenv
        make -f Makefile.dj
        cp djgpp/i586-pc-msdosdjgpp/bin/cwsdpmi.exe .

    - uses: actions/upload-artifact@v4
      with:
        name: djdemo
        path: |
          data/
          djdemo.exe
          cwsdpmi.exe

# vi:ts=2 sts=2 sw=2 expandtab:
