name: emscripten build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: mymindstorm/setup-emsdk@v14

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install subversion

    - name: prepare datafiles
      run: |
        svn export svn://mutantstargoat.com/datadirs/dosdemo data
        tools/procdata

    - name: build demo
      run: |
        make -f Makefile.em

    - uses: actions/upload-artifact@v4
      with:
        name: demo-emscripten
        path: |
          demo.html
          demo.js
          demo.wasm
          demo.data

# vi:ts=2 sts=2 sw=2 expandtab:
