name: DOS build (Watcom)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cache toolchain
      id: cache-tc
      uses: actions/cache@v3
      with:
        path: ow
        key: openwatcom-cache1

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpng-dev libjpeg-dev nasm

    - name: install toolchain
      if: steps.cache-tc.outputs.cache-hit != 'true'
      run: |
        wget http://mutantstargoat.com/~nuclear/ow_bundle.tar.gz
        tar xzvf ow_bundle.tar.gz
        sed -i 's/HOME/GITHUB_WORKSPACE/g' ow/owsetenv-dos.sh

    - name: prepare datafiles
      run: |
        svn export svn://mutantstargoat.com/datadirs/dosdemo data
        tools/procdata
    - name: build libs/imago
      run: |
        source ow/owsetenv-dos.sh
        cd libs/imago
        wmake
    - name: build libs/anim
      run: |
        source ow/owsetenv-dos.sh
        cd libs/anim
        wmake
    - name: build demo
      run: |
        source ow/owsetenv-dos.sh
        wmake
        cp ow/binw/dos4gw.exe .

    - uses: actions/upload-artifact@v3
      with:
        name: watdemo
        path: |
          data/
          demo.exe
          dos4gw.exe
